### ISSUE TITLE
RFC: Replace deprecated 'previewSession' method with 'getPreviewResolver'

### ISSUE THREAD

**Issue by phillysnow** [prismicio/reactjs-website#2]
We need to replace the previewSession method used for parsing preview cookies shown here:
https://github.com/prismicio/reactjs-blog/blob/master/src/pages/Preview.js

With the new getPreviewResolver which is documented here:
https://prismic.io/docs/reactjs/beyond-the-api/in-website-preview#16_0-processing-the-preview-token-with-getpreviewresolver-method

**Comment by levimykel** [comment]
Fixed with #3
